words = [
    'probability',
    'expected value',
    'insurance',
    'contingent',
    'term',
    'variance',
    'premium',
    'mortality',
    'gompertz',
    'makeham',
    'exponential',
    'recursion',
    'rate',
    'discount',
    'interest',
    'annuity',
    'payment',
    'benefit',
    'whole life',
    'deferred whole life',
    'pure endowment',
    'endowment insurance',
    'force of interest',
    'life table',
    'constant force of mortality',
    'present value',
    'uniform distribution of deaths',
    'discrete',
    'continuous',
    'net premium',
    'gross premium',
    'reserve',
    'expense reserve',
]
